### ISSUE TITLE
404 in custom-elements.json cause javascript debugger break 

### ISSUE THREAD

**Issue by timker** [Matsuuu/web-component-devtools#11] opened 2021-07-08 04:55 UTC
missing custom-element.json make my debugger kick into action

maybe check res.ok before calling json()

![image](https://user-images.githubusercontent.com/659555/124864072-6691e980-e00c-11eb-8494-62e5bbe59025.png)

**Comment by Matsuuu** [comment] 2021-07-08 12:02
I wasn't able to reproduce the debugger getting triggered by this.

Could you provide a minimal example or a link to a site in which this happens?

And what is your debugger setup?

**Comment by timker** [comment] 2021-07-08 21:35
Unfortunately the example site is behind a password, sorry

as far as dev tools set up, I ca't see anything weird

![image](https://user-images.githubusercontent.com/659555/124992844-9d611180-e097-11eb-908b-221f6b527618.png)

pause is unchecked

It seems to be intermittent today...?

Other Notes:
there is an tiny service worker
there are iframes

**Comment by Matsuuu** [comment] 2021-07-10 10:55
Heya,

Could you try out with the latest version (0.1.2) and see if it still happens?

**Comment by timker** [comment] 2021-07-15 00:03
Hey, Just tried in 0.1.3, still same issue.

**Comment by timker** [comment] 2021-07-15 00:07
FYI, great naming for nydus.js

**Comment by Matsuuu** [comment] 2021-07-16 11:46
Hey, thanks for checking in.

Unfortunately I'm not able to reproduce this.

Could you give clear steps on how you get this to happen?

**Comment by Matsuuu** [comment] 2021-07-23 17:21
In the next version the fetch requests are done by a background script, which should eliminate these errors. I'll ping this ticket as it ships

**Comment by Matsuuu** [comment] 2021-08-04 12:30
This should be fixed in 0.1.8

**Closed** 2021-08-04 12:29 UTC

**Comment by timker** [comment] 2021-08-17 21:22
hey ya, just re-enabled and 0.1.9 no longer has the issue.

Thanks for fixing, keep up the good work
